
Running tests... 
----------------------------------------------------------------------
 test_baidu (test_baidu.My_Test) ... OK (10.512000)s
 test_youdao (test_youdao.MyTest) ... ERROR (15.679000)s

======================================================================
ERROR [15.679000s]: test_youdao.MyTest.test_youdao
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hss\workgit\hellopython\test_project\test_case\test_youdao.py", line 17, in test_youdao
    driver.find_element_by_id('query').clear()
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 234, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"query"}
  (Session info: chrome=75.0.3770.80)
  (Driver info: chromedriver=72.0.3626.69 (3c16f8a135abc0d4da2dff33804db79b849a7c38),platform=Windows NT 6.1.7601 SP1 x86_64)


----------------------------------------------------------------------
Ran 2 tests in 0:00:26

FAILED
 (Errors=1)

Generating HTML reports... 
reports\TestResults_test_baidu.My_Test_2019-08-07_17-12-45.html
reports\TestResults_test_youdao.MyTest_2019-08-07_17-12-45.html
